version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    build: frontend # specify the directory of the Dockerfile
    ports:
      - "8181:80" # specify port forewarding
    links:
      - express
  
  express: #name of the second service
    build: api-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://database:27017/its_2023_cart

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27018:27017" # specify port forewarding
    volumes:
      - ./mongo/data:/data/db