# Stage 1
# Create image based on the official Node 12 image from dockerhub
FROM node:lts-alpine as build

# Create a directory where our app will be placed
RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY package*.json ./

# Install dependecies
RUN npm install

# Get all the code needed to run the app
COPY . .

# Run the angular in production mode
RUN npm run build

FROM node:lts-alpine

RUN mkdir -p /usr/src/app

# Change directory so that our commands run inside this new directory
WORKDIR /usr/src/app

# Copy dist content to html nginx folder, config nginx to point in index.html
COPY --from=build /usr/src/app/dist .

COPY --from=build /usr/src/app/package.json .

RUN npm install --production

CMD [ "node", "./index.js" ];

